In [2]:
import numpy as np

# Define the input data
X = np.array([[2, 9], [1, 5], [3, 6]], dtype=float)
y = np.array([[92], [86], [89]], dtype=float)
X = X/np.amax(X, axis=0)
y = y/100

# Define the sigmoid function and its derivative
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def derivatives_sigmoid(x):
    return x * (1 - x)

# Initialize variables
epoch = 5000  # Number of training iterations
lr = 0.1  # Learning rate

# Define the network architecture
inputlayer_neurons = 2  # Number of features in dataset
hiddenlayer_neurons = 3  # Number of neurons in the hidden layer
output_neurons = 1  # Number of neurons in the output layer

# Initialize weights and biases
wh = np.random.uniform(size=(inputlayer_neurons, hiddenlayer_neurons))
bh = np.random.uniform(size=(1, hiddenlayer_neurons))
wout = np.random.uniform(size=(hiddenlayer_neurons, output_neurons))
bout = np.random.uniform(size=(1, output_neurons))

# Training loop
for i in range(epoch):
    # Forward propagation
    hinpl = np.dot(X, wh)
    hinp = hinpl + bh
    hlayer_act = sigmoid(hinp)

    outinpl = np.dot(hlayer_act, wout)
    outinp = outinpl + bout
    output = sigmoid(outinp)

    # Backpropagation
    EO = y - output
    outgrad = EO * derivatives_sigmoid(output)
    EH = np.dot(outgrad, wout.T)
    hiddengrad = EH * derivatives_sigmoid(hlayer_act)

    # Update weights and biases
    wout += np.dot(hlayer_act.T, outgrad) * lr
    wh += np.dot(X.T, hiddengrad) * lr

# Print the final output
print("Input: \n" + str(X))
print("\n")
print("Actual Output: \n" + str(y))
print("\n")
print("Predicted Output: \n", output)

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]


Actual Output: 
[[0.92]
 [0.86]
 [0.89]]


Predicted Output: 
 [[0.89573433]
 [0.87985372]
 [0.89426475]]


In [3]:
import numpy as np

# Define the input data (changed inputs)
data = np.array([[4, 12], [2, 8], [6, 7]], dtype=float)  # Example input
target = np.array([[95], [88], [91]], dtype=float)  # Example output
data = data / np.amax(data, axis=0)  # Normalize the input data
target = target / 100  # Normalize the target output

# Define the sigmoid function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def derivatives_sigmoid(x):
    return x * (1 - x)

# Initialize variables
epochs = 5000  # Number of training iterations
learning_rate = 0.1  # Learning rate

# Define the network architecture (new architecture)
num_input_features = 2  # Number of features in the dataset
num_hidden_neurons = 3  # Number of neurons in the hidden layer
num_output_neurons = 1  # Number of neurons in the output layer

# Initialize weights and biases
weights_hidden = np.random.uniform(size=(num_input_features, num_hidden_neurons))  # Weights for input to hidden layer
bias_hidden = np.random.uniform(size=(1, num_hidden_neurons))  # Bias for hidden layer
weights_output = np.random.uniform(size=(num_hidden_neurons, num_output_neurons))  # Weights for hidden to output layer
bias_output = np.random.uniform(size=(1, num_output_neurons))  # Bias for output layer

# Training loop
for epoch in range(epochs):
    # Forward propagation
    hidden_input = np.dot(data, weights_hidden) + bias_hidden
    hidden_layer_output = sigmoid(hidden_input)

    output_input = np.dot(hidden_layer_output, weights_output) + bias_output
    predicted_output = sigmoid(output_input)

    # Backpropagation
    error_output = target - predicted_output
    output_gradient = error_output * derivatives_sigmoid(predicted_output)
    error_hidden = np.dot(output_gradient, weights_output.T)
    hidden_gradient = error_hidden * derivatives_sigmoid(hidden_layer_output)

    # Update weights and biases
    weights_output += np.dot(hidden_layer_output.T, output_gradient) * learning_rate
    weights_hidden += np.dot(data.T, hidden_gradient) * learning_rate

# Print the final output
print("Input Data: \n" + str(data))
print("\n")
print("Actual Output: \n" + str(target))
print("\n")
print("Predicted Output: \n", predicted_output)


Input Data: 
[[0.66666667 1.        ]
 [0.33333333 0.66666667]
 [1.         0.58333333]]


Actual Output: 
[[0.95]
 [0.88]
 [0.91]]


Predicted Output: 
 [[0.92019675]
 [0.90081375]
 [0.91712589]]
